### PR TITLE
Fixed incorrect css parsing when value for url() contains data with parentheses

### PR DESCRIPTION
**Pull request by nqxcode**
Fixed incorrect parsing for this example: url("data: ... ()")

### CODE REVIEW

**Comment by natxet** [comment]
Hey, can you commit without the gitignore please? Looks that you're ignoring OsX and PHP typical files. By the way, those should be ignored in your local gitignore file so you don't need to add it to .gitignore on each project ;-) Thanks for your help!

**Comment by nqxcode** [comment]
Ok

**Comment by natxet** [comment]
Thanks!

**Comment by adoerler** [comment]
Great, thanks for providing a fix and merging it into master. I've just had this very same problem tonight after integrating Swiper JS which contains somesthing like `rotate(300%2060%2C60)` in the background-image url values.

Kind regards from Austria
Andreas

**Comment by nqxcode** [comment]
Whether the new release with this fix is planned?

**Pull request merged**
